### ISSUE TITLE
Run check on a local package

### ISSUE THREAD

**Issue by traversc** [kalibera/rchk#20]
Is it possible to run rchk on a local package?  The readme explains how to run it on a package already on CRAN, but I'd like to run it before submitting, so I don't waste anybody's time (Dr. Ligges, etc.)

Not familiar with the tools used, so sorry if this is a simple question.

**Comment by kalibera** [comment]
Yes, you can check a tarball locally, see https://github.com/kalibera/rchk
Try `singularity pull shub://kalibera/rchk:def` on a fast network and then `singularity run kalibera-rchk-master-def.simg tarball.tgz` (or whatever is the name of the downloaded image with your version of singularity). If that does not work right away, please check out the documentation at https://github.com/kalibera/rchk
