### ISSUE TITLE
Installation (Fedora 34): missing  `llvm/Support/StringPool.h`

### ISSUE THREAD

**Issue by mmaechler** [kalibera/rchk#26]
I've followed the installation instructions for `Fedora 32`  
      https://github.com/kalibera/rchk/blob/master/doc/INSTALLATION.md#fedora-32
but have F 34.
- All '0-level' dependencies were already present (i.e.  gave  `Nothing to do.`)
- Step 1 ended successfully in
```
Installed:
  llvm-devel-12.0.1-1.fc34.x86_64        llvm-static-12.0.1-1.fc34.x86_64       
  llvm-test-12.0.1-1.fc34.x86_64        

Complete!
```

- Step 2  (python pip ..) success ending in
```
Installing collected packages: wllvm
Successfully installed wllvm-1.3.1
```

- Now, step 3, the installation of `rchk` failed during make, specifically
```
g++ -I/usr/include -std=c++14 -fno-exceptions -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -O3 -g3 -MMD -DBCHECK_MAX_STATES=3000000 -DCALLOCATORS_MAX_STATES=1000000 -I/usr/include/llvm-3.8/ -I/usr/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS  -c -o allocators.o allocators.cpp
In file included from guards.h:17,
                 from callocators.h:9,
                 from exceptions.h:5,
                 from allocators.cpp:3:
linemsg.h:14:10: fatal error: llvm/Support/StringPool.h: No such file or directory
   14 | #include <llvm/Support/StringPool.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: allocators.o] Error 1
```
and searching for the missing header in the installed  `llvm-devel` package indeed showed it was *not* installed:
```
root@lynne rchk#  dnf repoquery -l llvm-devel | sed -n '1,3p; /StringPool.h/p'
Updating Subscription Management repositories.
Last metadata expiration check: 0:07:39 ago on Thu 09 Sep 2021 09:47:06 AM CEST.
/usr/bin/llvm-config
/usr/bin/llvm-config-32
/usr/include/llvm/ExecutionEngine/Orc/SymbolStringPool.h
/usr/include/llvm/ExecutionEngine/Orc/SymbolStringPool.h
/usr/include/llvm/ExecutionEngine/Orc/SymbolStringPool.h
/usr/include/llvm/ExecutionEngine/Orc/SymbolStringPool.h
```
and yes, it is `rchk` itself asking for that header:
```
root@lynne rchk# grep -rn -F StringPool.h
src/linemsg.h:14:#include <llvm/Support/StringPool.h>
```
As I'm really not knowledgable in versions of  `llvm`   
*and* as this is not really urgent,  I'm giving up for now,  but of course will try things if instructed
... for a time *after* the new RWin toolchain installer is released

**Comment by kalibera** [comment]
Thank you, Martin, for the report. Fedora 34 comes with LLVM11, which made a number of changes in the API to which rchk will have to be adapted, so it will take some more time. rchk is using the LLVM library to analyze compiled R packages (the binary code, compiler to LLVM IR), so it is using directly LLVM headers, and this particular header was probably removed. But there are other changes (e.g. CallSite object has been removed, StringRef objects work differently, etc).

**Comment by mmaechler** [comment]
No hurry, really!   I don't have any pressing need and I know the are more important things currently for you.

**Comment by kalibera** [comment]
I've created a branch named `llvm11` with the necessary changes, so perhaps you would just need to run "make clean", switch to the branch, and "make" again. It still has to be documented and tested on more R packages, but it worked fine for me on base R + recommended packages, and I've compared the reports with those provided using an older version of rchk and LLVM.

**Comment by kalibera** [comment]
I've now expanded the documentation with instructions for Fedora 33, Fedora 34 and Debian Bookworm, to address building on LLVM11 and LLVM12.
