### ISSUE TITLE
Incorrect analysis around C++ constructors and destructors

### ISSUE THREAD

**Issue by david-cortes** [kalibera/rchk#27]
I'm experiencing what I think is a false alarm in `rchk` from what I guess is a trivial case to analyze and perhaps a common usage of R calls.

In short, I have a C++ class which allocates and protects an R object in its constructor, and then unprotects it in its destructor. The underlying `SEXP` might be value-assigned to a struct in the middle of the object lifetime without involving any extra protection (e.g. `new_struct.sexp_obj = wrapper_class.sexp_obj`), and there is some potential calls to `Rf_error` in case of errors.

This situation triggers `[PB] has negative depth` in the constructor and `[UP] attempt to unprotect more items (1) than protected (0)` in the destructor.

This is the code for the class:
https://github.com/david-cortes/LightGBM/blob/4c757534905a6029288767ba25de7751c4860a29/R-package/src/lightgbm_R.cpp#L51

And this is how it is used:
https://github.com/david-cortes/LightGBM/blob/4c757534905a6029288767ba25de7751c4860a29/R-package/src/lightgbm_R.cpp#L228

Usage of C++ objects is wrapped in a `#define`'d try-catch block:
https://github.com/david-cortes/LightGBM/blob/4c757534905a6029288767ba25de7751c4860a29/R-package/src/lightgbm_R.cpp#L34

I've tried different variations, such as:

* Setting a boolean telling whether to call `UNPROTECT` and leaving it to false in the destructor, in case the destructor somehow ends up being called more than once.
* Using more explicit object construction - e.g. `MyObj obj = MyObj()` vs. just `MyObj obj` (although I'm quite certain it should be the same in C++>=11).
* Moving the C++ object which has `PROTECT`/`UNPROTECT` in its constructor/destructor to inside a try-catch block.

But all of them result in a warning.

**Comment by kalibera** [comment]
One would need a complete reproducible example to analyze why the tool issues the warning. From you description I can only speculate, based on experience with analyzing similar issues, that the problem is related to that the tool does not know which functions may throw which exceptions. The tool hence conservatively assumes that exceptions can occur at any time within a `try` block, which may lead to false alarms. I've seen several instances so far where moving the PROTECT/UNPROTECT outside of the try block produced simpler code for humans and also made the tool happy, but I don't want to claim this is always the case. Adding some exceptions analysis would probably improve the quality of the reports for some C++ code, but I am not sure by how much, it may not be worth the effort.

**Comment by david-cortes** [comment]
Attached is a smaller example (C++ code and full package). I don't think it is related to exceptions, since the object that has the protections in the constructor/destructor is allocated outside of a try-catch block.

```cpp
#include <vector>
#include <random>
#include <cstdio>
#include <string>
#include <cstring>
#include <R.h>
#include <Rinternals.h>

char errmsg_buffer[256];

class WrapperUnwindToken {
public:
    SEXP token;

    WrapperUnwindToken()
    {
        this->token = PROTECT(R_MakeUnwindCont());
    }

    ~WrapperUnwindToken()
    {
        UNPROTECT(1);
    }
};

struct R_errclass {SEXP token;};

void R_err_to_cpp_ex(void *ptr_cont_token, Rboolean jump)
{
    if (jump)
    {
        throw R_errclass{static_cast<WrapperUnwindToken*>(ptr_cont_token)->token};
    }
}

SEXP wrapped_Rvector(void *size)
{
    return Rf_allocVector(REALSXP, *static_cast<R_xlen_t*>(size));
}

SEXP protected_Rvector(R_xlen_t size, WrapperUnwindToken *uw_token)
{
    return R_UnwindProtect(
        wrapped_Rvector, static_cast<void*>(&size), R_err_to_cpp_ex,
        static_cast<void*>(uw_token), uw_token->token
    );
}

SEXP test_cppfun(SEXP veclen, SEXP seed)
{
    WrapperUnwindToken unwind_token;
    try
    {
        int veclen_ = Rf_asInteger(veclen);
        int seed_ = Rf_asInteger(seed);
        std::vector<double> myvec(veclen_);
        std::default_random_engine rng(seed_);
        std::normal_distribution<double> rnorm(0, 1);
        for (auto &el : myvec)
            el = rnorm(rng);
        for (int ix = 1; ix < myvec.size(); ix++)
            myvec[ix] += myvec[ix-1];
        SEXP Rvec = PROTECT(protected_Rvector(veclen_, &unwind_token));
        std::memcpy(REAL(Rvec), myvec.data(), veclen_*sizeof(double));
        UNPROTECT(1);
        return Rvec;
    }

    catch (WrapperUnwindToken &err) {
        R_ContinueUnwind(err.token);
    }

    catch(std::exception &e) {
        std::sprintf(errmsg_buffer, "%s\n", e.what());
    }

    catch(std::string &e) {
        std::sprintf(errmsg_buffer, "%s\n", e.c_str());
    }

    catch(...) {
        Rf_error("Unknown error.\n");
    }
    Rf_error(errmsg_buffer);
    return R_NilValue;
}

extern "C"
{

static const R_CallMethodDef callMethods [] = {
    {"test_cppfun", (DL_FUNC) &test_cppfun, 2},
    {NULL, NULL, 0}
}; 

void R_init_Rcheckme(DllInfo *info)
{
    R_registerRoutines(info, NULL, callMethods, NULL, NULL);
    R_useDynamicSymbols(info, TRUE);
}

}
```
[Rcheckme_0.0.1.tar.gz](https://github.com/kalibera/rchk/files/7214328/Rcheckme_0.0.1.tar.gz)

Output:
```
Library name (usually package name): Rcheckme
Initialization function: R_init_Rcheckme
Functions: 1
Checked call to R_registerRoutines: 1
ERROR: too many states (abstraction error?) in function strptime_internal

Function WrapperUnwindToken::WrapperUnwindToken()
  [PB] has possible protection stack imbalance /rchk/packages/build/r1p8HYBo/Rcheckme/src/cpp_file.cpp:18

Function WrapperUnwindToken::~WrapperUnwindToken()
  [PB] has negative depth /rchk/packages/build/r1p8HYBo/Rcheckme/src/cpp_file.cpp:22
  [UP] attempt to unprotect more items (1) than protected (0), results will be incomplete /rchk/packages/build/r1p8HYBo/Rcheckme/src/cpp_file.cpp:22
  [PB] has possible protection stack imbalance /rchk/packages/build/r1p8HYBo/Rcheckme/src/cpp_file.cpp:23
Analyzed 113 functions, traversed 224 states.
```

**Comment by kalibera** [comment]
Thanks for the example, I get the question now. Rchk requires that functions are balanced wrt to protection. It reports some cases when they are not, but it also depends on that they are balanced in how it models the code.

The constructor and destructor  in the example are not balanced, which the tool reports. The constructor is protecting an object before returning it, but objects should be returned unprotected by functions that allocate them. The destructor is unprotecting more than protecting, touching the protect stack of the caller, which is not allowed for functions.

The R protection API and requirements were designed for C, as R has a C API, where these requirements make perfect sense. With C++, naturally, one would want to allow automated unprotection in destructors, and hence imbalance in destructors, and what is much less clear then also allow imbalance somehow on the way to the constructor and in the constructor, perhaps. Rchk does not support any of that and it would be a lot of work to implement. In either case, this would have to start by defining a C++ R protection API and semantics, and then implement that in (possibly a rewrite of) rchk. And then it would require things I mentioned before - some analysis of exceptions, some class-hierarchy analysis, etc.

If you wanted to make rchk completely happy, you would probably have to move the PROTECT/UNPROTECT calls to the test_cppfun, and refrain from using the destructor for automated unprotection, so the protection stuff would have to be kept outside constructors and destructors.  I don't have a strong opinion what the C++ R protection API should be. One can protect like in your example, or one can also have an extra object doing the protection, such as in Rcpp (Shelter, Armor, Shield), but even then at least those objects would receive the warnings. Also, with the current R protection API and semantics with C++, you have the problem that destructors can destroy your return value when they call an allocating function, which is a common C++-specific protection bug which is (almost surprisingly) sometimes found by the tool. Sometimes it is found much harder way by debugging memory corruption, or via UBSAN.

**Comment by kalibera** [comment]
In any case, packages using C++ this way and getting warnings in CRAN checks may be excluded from the CRAN checks (I've now added lightgbm to the list). One can still manually check the full reports for possibly masked true positives.
