### ISSUE TITLE
Explicit protection cancels implicit protection

### ISSUE THREAD

**Issue by lionel-** [kalibera/rchk#30]
This is a minimal reprex. The pattern might occur in realistic cases via macros:

```c
// Function foo
//   [UP] unprotected variable x while calling allocating function Rf_allocVector

SEXP foo(SEXP x) {
  PROTECT(x);
  UNPROTECT(1);

  Rf_allocVector(INTSXP, 1);

  return x;
}
```

**Comment by kalibera** [comment]
The tool does not attempt to detect when objects are protected unnecessarily, it wants to find cases where they are not protected when they should be. There is a heuristic that if an object has been protected explicitly, there was probably a good reason for it, one that the tool does not see. Hence, once unprotected then explicitly, the object is probably no longer protected, even though the tool does not know why. So this biases towards more true errors for the price of showing some reports which are technically false alarms, but can still be useful (e.g. in the code above, the unnecessary explicit protection is confusing to the reader). It worked well on the code I've been tuning/debugging this on, but yes, it won't work well on generated code.

**Comment by lionel-** [comment]
It seems to me that the tool was fine tuned at a certain point in time on existing practice on C packages (not C++ ones which, again, are free to use whatever protection schemes they like in their ctors) and now we're stuck with the idioms in place at that time.

As it stands, rchk makes it difficult for C packages to use a general protect-by-assignment scheme. I'll just disable rchk via pointer taken in large initialisation routines where protect-by-assignment makes the code easier to maintain. I otherwise love rchk, it's an invaluable tool and I am grateful for it. It has found many bugs in my code. I just wish it would be more helpful by letting C APIs define their local protection schemes. You'll not be losing anything by being more flexible. The bulk of native code is happening in C++ not C anyway.
