### ISSUE TITLE
How to safely get raw pointer

### ISSUE THREAD

**Issue by jeroen** [kalibera/rchk#4]
The new rchk produces a lot of [these](https://raw.githubusercontent.com/kalibera/cran-checks/master/rchk/results/openssl.out) for me. I never knew that `RAW()` may allocate. Is there an alternative api to get the raw pointer of an object that is safe?

**Comment by kalibera** [comment]
Thanks for spotting this, the tool was confused by ALTREP changes. RAW() does not allocate. Should be fixed now, but it will take some time for the results to update.
